Repository googleapis/python-spanner-django, pull requests merged in 2020-09, with the labels that each got.

#463 feat: cursor must detect if the parent connection is closed
  spanner_dbapi/connection.py
  spanner_dbapi/cursor.py
  tests/spanner_dbapi/test_connection.py
  tests/spanner_dbapi/test_cursor.py
Labels: api: spanner, cla: yes, type: feature request

#480 feat: Stage 6 of `nox` implementation - enabling system tests
  .gitignore
  noxfile.py
  tests/system/__init__.py
  tests/system/test_system.py
Labels: api: spanner, cla: yes, type: process

#487 chore: Code refactoring to follow common Google API scheme - Stage I
  django_spanner/base.py
  django_spanner/operations.py
  google/__init__.py
  google/cloud/__init__.py
  google/cloud/spanner_dbapi/__init__.py
  google/cloud/spanner_dbapi/connection.py
  google/cloud/spanner_dbapi/cursor.py
  google/cloud/spanner_dbapi/exceptions.py
  google/cloud/spanner_dbapi/parse_utils.py
  google/cloud/spanner_dbapi/parser.py
  google/cloud/spanner_dbapi/types.py
  google/cloud/spanner_dbapi/utils.py
  google/cloud/spanner_dbapi/version.py
  noxfile.py
  tests/spanner_dbapi/test_connect.py
  tests/spanner_dbapi/test_connection.py
  tests/spanner_dbapi/test_cursor.py
  tests/spanner_dbapi/test_globals.py
  tests/spanner_dbapi/test_parse_utils.py
  tests/spanner_dbapi/test_parser.py
  tests/spanner_dbapi/test_types.py
  tests/spanner_dbapi/test_utils.py
  tests/spanner_dbapi/test_version.py
Labels: api: spanner, cla: yes

#489 fix: Change release script package name
  .kokoro/release.sh
Labels: cla: yes

#503 fix: Update README for alpha release
  README.rst
Labels: api: spanner, cla: yes

#506 fix: Update version to 2.2.0a1
  django_spanner/base.py
  docs/conf.py
  google/cloud/spanner_dbapi/version.py
  setup.py
  version.py
Labels: cla: yes

#509 fix: Fix typo in README
  README.rst
Labels: cla: yes

#507 fix: Fix license classifier
  setup.py
Labels: cla: yes

#511 fix: Fix typo in README
  README.rst
Labels: cla: yes

#504 refactor: erase strip_backticks() helper
  google/cloud/spanner_dbapi/parse_utils.py
  tests/spanner_dbapi/test_parse_utils.py
Labels: api: spanner, cla: yes, type: cleanup

#488 refactor: update classify_stmt() helper and cover it with unit tests
  google/cloud/spanner_dbapi/parse_utils.py
  tests/spanner_dbapi/test_parse_utils.py
Labels: api: spanner, cla: yes, type: process

#513 refactor: small changes in parse_utils
  google/cloud/spanner_dbapi/parse_utils.py
Labels: api: spanner, cla: yes, type: process

#519 chore: add default CODEOWNERS
  .github/CODEOWNERS
Labels: api: spanner, cla: yes

#508 fix: Replace repo name with pkg name
  README.rst
  docs/conf.py
Labels: api: spanner, cla: yes

#515 docs: add a querying example into the main readme
  README.rst
Labels: api: spanner, cla: yes, type: docs

#517 refactor: update and document Cursor.executemany() method, add unit t…
  google/cloud/spanner_dbapi/cursor.py
  tests/spanner_dbapi/test_cursor.py
Labels: api: spanner, cla: yes, type: process
