Repository googleapis/python-spanner-django, pull requests merged in 2021-02, with the labels that each got.

#593 fix: Remove old quickstart instructions link
  examples/from-scratch/README.md
Labels: api: spanner, cla: yes

#591 refactor: Erase excess code in build scripts
  .kokoro/build.sh
  .kokoro/ensure_instance_exists.py
  django_test_suite.sh
Labels: api: spanner, cla: yes, type: cleanup

#596 fix: Bump version number after 2.2.1b0 release
  version.py
Labels: api: spanner, cla: yes

#598 fix: Replace, fast-forward Django CI branch
  .kokoro/build.sh
  django_test_suite.sh
Labels: api: spanner, cla: yes

#599 chore: README updates
  README.rst
Labels: cla: yes

#600 chore: Add "contributing" section to README
  README.rst
Labels: cla: yes

#601 chore: Remove README note about Variance/StdDev
  README.rst
Labels: cla: yes
