Repository googleapis/python-spanner-django, pull requests merged in 2022-07, with the labels that each got.

#766 chore: change repo maintainer
  .github/blunderbuss.yml
Labels: automerge, api: spanner

#775 fix: decrease query param chunk size
  django/db/models/query.py
Labels: api: spanner

#777 fix: decrease batch size
  django/db/models/query.py
  tests/bulk_create/tests.py
Labels: api: spanner

#776 tests: skip batching tests inapproriate for Spanner
  tests/bulk_create/tests.py
Labels: api: spanner

#772 chore: use stable django versions for tests hosted on python-spanner-django
  .github/sync-repo-settings.yaml
  django_test_suite.sh
  django_test_suite_3.2.sh
  noxfile.py
Labels: api: spanner

#780 fix: override AutoField default value only for Spanner
  django_spanner/__init__.py
  tests/unit/django_spanner/test_schema.py
Labels: type: bug, api: spanner
